version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  web:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  


volumes:
  pgdata: